POST http://localhost:3001/api/contracts HTTP/1.1
content-type: application/json

{
  "participantName": "example-participant-foo",
  "contractType": "consumer",
  "contract": {
    "consumer": {
      "name": "example-participant-foo"
    },
    "provider" : {
      "name": "example-participant-buzz"
    }
  },
  "contractFormat": "json",
  "participantVersion": "1.1.3",
  "participantBranch": "main"
}

###

POST http://localhost:3001/api/contracts HTTP/1.1
content-type: application/json

{
  "participantName": "example-participant-buzz",
  "contractType": "provider",
  "contract": {
    "hello": "world"
  },
  "contractFormat": "json",
  "participantVersion": "2.3.1",
  "participantBranch": "dev"
}

###
GET http://localhost:3001/test8
content-type: application/json

{
  "joinGraph": "[consumer.versions.contract, provider]",
  "where": [
    "integrationId",
    "=",
    2
  ]
}

###
GET http://localhost:3001/api/contracts/1
content-type: application/json

{
  "joinGraph": ["owner.versions", "participantVersions"]
}

###
GET http://localhost:3001/api/contracts/1
content-type: application/json
