POST http://localhost:3001/api/contracts HTTP/1.1
content-type: application/json

{
  "participantName": "example-participant-bar",
  "contractType": "consumer",
  "contract": {
    "consumer": {
      "name": "example-participant-bar"
    },
    "provider" : {
      "name": "example-participant-buzz"
    }
  },
  "contractFormat": "json",
  "participantVersion": "1.0.0",
  "participantBranch": "main"
}

###

POST http://localhost:3001/api/contracts HTTP/1.1
content-type: application/json

{
  "participantName": "example-participant-bar",
  "contractType": "provider",
  "contract": {
    "hello": "world"
  },
  "contractFormat": "json",
  "participantVersion": "2.0.0",
  "participantBranch": "dev"
}
